name: "Setup and build the repo"
description: "A task to reuse setup steps during multiple jobs"
inputs:
  node:
    description: Node version
    required: true

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: ${{inputs.node}}
        check-latest: true
        # Due to a known issue we have to disable package caching for now
        # https://github.com/pnpm/pnpm/issues/6234
        # cache: pnpm
        package-manager-cache: false

    - name: Node.js version
      id: node
      shell: bash
      run: echo "v8CppApiVersion=$(node --print "process.versions.modules")" >> $GITHUB_OUTPUT

    - name: Create cache key
      id: build-cache
      shell: bash
      # This build cache will be reused among different jobs for the same commit
      run: echo "key=build-cache-${{ runner.os }}-${{ runner.arch }}-node-${{ inputs.node }}-${{ github.sha }}" >> $GITHUB_OUTPUT

    - name: Restore build
      uses: actions/cache/restore@v4
      id: cache-build-restore
      with:
        path: |
          lib/
          packages/*/lib
          packages/*/.git-data.json
        key: ${{ steps.build-cache.outputs.key }}

    - name: Install & build
      shell: bash
      run: pnpm install --frozen-lockfile && pnpm build

    - name: Check Build
      shell: bash
      run: pnpm check-build

    - name: Build bundle
      shell: bash
      run: pnpm build:bundle

    - name: Check bundle
      shell: bash
      run: pnpm check-bundle

    - name: Cache build artifacts
      uses: actions/cache@v4
      with:
        path: |
          lib/
          packages/*/lib
          packages/*/.git-data.json
        key: ${{ steps.build-cache.outputs.key }}
